### 상품 추가
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaVzd4Y01NdHloZVlmaG5pTndPdlU4Mi9xWXZhcWtvcGcrcW9vZkFLRkp3PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMjY0MjM5LCJleHAiOjE2ODAzNTA2Mzl9.RTfsHc3b5co6m7mtqjQeYYb36Co62l0e7yfiB16UpaA

{
  "description": "description",
  "items": [
    {
      "count": 1,
      "name": "270",
      "price": 100000
    }
  ],
  "name": "nike airForce 2"
}

### 상품 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaVzd4Y01NdHloZVlmaG5pTndPdlU4Mi9xWXZhcWtvcGcrcW9vZkFLRkp3PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMjY0MjM5LCJleHAiOjE2ODAzNTA2Mzl9.RTfsHc3b5co6m7mtqjQeYYb36Co62l0e7yfiB16UpaA

{
  "productId": 1,
  "count": 1,
  "name": "280",
  "price": 100000
}

### 상품 수정
PUT http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaVzd4Y01NdHloZVlmaG5pTndPdlU4Mi9xWXZhcWtvcGcrcW9vZkFLRkp3PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMjY0MjM5LCJleHAiOjE2ODAzNTA2Mzl9.RTfsHc3b5co6m7mtqjQeYYb36Co62l0e7yfiB16UpaA

{
  "description": "description",
  "items": [
    {
      "id": 1,
      "count": 1,
      "name": "270",
      "price": 100000
    }
  ],
  "id": 1,
  "name": "nike airForce limited"
}

### 상품 아이템 수정
PUT http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaVzd4Y01NdHloZVlmaG5pTndPdlU4Mi9xWXZhcWtvcGcrcW9vZkFLRkp3PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMjY0MjM5LCJleHAiOjE2ODAzNTA2Mzl9.RTfsHc3b5co6m7mtqjQeYYb36Co62l0e7yfiB16UpaA

{
  "id": 1,
  "count": 1,
  "name": "280",
  "price": 100000
}


### 상품 삭제
DELETE http://localhost:8082/seller/product?id=1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaVzd4Y01NdHloZVlmaG5pTndPdlU4Mi9xWXZhcWtvcGcrcW9vZkFLRkp3PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMDgzNTQwLCJleHAiOjE2ODAxNjk5NDB9.LLzwYVmREbkxmC2f5v-Y5-ciO6SKymiJPpWKucZW58E

{
  "description": "description",
  "items": [
    {
      "id": 1,
      "count": 1,
      "name": "270",
      "price": 100000
    }
  ],
  "id": 1,
  "name": "nike airForce limited"
}

### 상품 아이템 삭제
DELETE http://localhost:8082/seller/product/item?id=1
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaVzd4Y01NdHloZVlmaG5pTndPdlU4Mi9xWXZhcWtvcGcrcW9vZkFLRkp3PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMDgzNTQwLCJleHAiOjE2ODAxNjk5NDB9.LLzwYVmREbkxmC2f5v-Y5-ciO6SKymiJPpWKucZW58E

### 상품 검색
GET http://localhost:8082/search/product?name=nike
Content-Type: application/json


### 상품 디테일 검색
GET http://localhost:8082/search/product/detail?productId=1
Content-Type: application/json

### 장바구니 추가
POST http://localhost:8082/customer/cart
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaVzd4Y01NdHloZVlmaG5pTndPdlU4Mi9xWXZhcWtvcGcrcW9vZkFLRkp3PSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjgwMjY0MjM5LCJleHAiOjE2ODAzNTA2Mzl9.RTfsHc3b5co6m7mtqjQeYYb36Co62l0e7yfiB16UpaA

{
  "description": "description",
  "id": 1,
  "items": [
    {
      "count": 1,
      "id": 1,
      "name": "270",
      "price": 100000
    }
  ],
  "name": "string",
  "sellerId": 1
}